/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopagos;

import java.awt.Window;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.FocusManager;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
/**
 *
 * @author ferna
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */int ncuotas=0;
     int cfactura=0;
     int ccontrato=0;
    public Venta() {
        initComponents();
    }

    public void ingreso()
    {
        JOptionPane.showMessageDialog(null, "SE CREO FACTURA CON EXITO\n"+"CODIGO DE FACTURA: "+cfactura);
        JOptionPane.showMessageDialog(null,"SE CREO CONTRATO CON EXITO\n"+"CODIGO DE CONTRATO: "+ccontrato);
        incliente.setText("");
        inproducto.setText("");
        mcliente.setText("");
        idir.setText("");
        init.setText("");
        mproducto.setText("");
        mprecio.setText("");
        mcuota.setText("");
        incliente.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupocuotas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        incliente = new javax.swing.JTextField();
        precio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inproducto = new javax.swing.JTextField();
        mproducto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mprecio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mcuota = new javax.swing.JLabel();
        bcliente = new javax.swing.JButton();
        bproducto = new javax.swing.JButton();
        ccliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mcliente = new javax.swing.JLabel();
        init = new javax.swing.JLabel();
        ccuotas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        docec = new javax.swing.JRadioButton();
        tresc = new javax.swing.JRadioButton();
        diezc = new javax.swing.JRadioButton();
        seisc = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Codigo Cliente");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 30, 130, 14);

        incliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inclienteActionPerformed(evt);
            }
        });
        incliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inclienteKeyPressed(evt);
            }
        });
        jPanel1.add(incliente);
        incliente.setBounds(40, 50, 137, 30);
        jPanel1.add(precio);
        precio.setBounds(777, 129, 0, 24);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CODIGO PRODUCTO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(38, 276, 108, 14);

        inproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inproductoActionPerformed(evt);
            }
        });
        inproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inproductoKeyPressed(evt);
            }
        });
        jPanel1.add(inproducto);
        inproducto.setBounds(40, 300, 137, 30);
        jPanel1.add(mproducto);
        mproducto.setBounds(40, 340, 196, 24);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CANTIDAD DE CUOTAS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(38, 414, 123, 14);

        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu);
        menu.setBounds(170, 570, 115, 47);

        ingresar.setText("Grabar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar);
        ingresar.setBounds(30, 570, 119, 47);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PRECIO DEL PRODUCTO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 280, 128, 10);

        mprecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(mprecio);
        mprecio.setBounds(300, 310, 144, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("MONTO DE CADA CUOTA");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 420, 152, 14);

        mcuota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(mcuota);
        mcuota.setBounds(300, 450, 152, 20);

        bcliente.setText("Buscar Cliente");
        bcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclienteActionPerformed(evt);
            }
        });
        jPanel1.add(bcliente);
        bcliente.setBounds(40, 90, 142, 23);

        bproducto.setText("Buscar Producto");
        bproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bproductoActionPerformed(evt);
            }
        });
        jPanel1.add(bproducto);
        bproducto.setBounds(40, 370, 127, 23);

        ccliente.setText("Crear Cliente");
        ccliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cclienteActionPerformed(evt);
            }
        });
        jPanel1.add(ccliente);
        ccliente.setBounds(190, 90, 139, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DIRECCION");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(38, 162, 61, 14);

        idir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idirActionPerformed(evt);
            }
        });
        jPanel1.add(idir);
        idir.setBounds(38, 182, 241, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("NIT");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 220, 66, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("NOMBRE Y APELLIDO");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(38, 115, 113, 14);
        jPanel1.add(mcliente);
        mcliente.setBounds(38, 135, 252, 21);
        jPanel1.add(init);
        init.setBounds(40, 240, 241, 23);

        ccuotas.setText("Calcular Pago de Cuotas");
        ccuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccuotasActionPerformed(evt);
            }
        });
        jPanel1.add(ccuotas);
        ccuotas.setBounds(40, 520, 200, 30);

        jPanel2.setLayout(null);

        grupocuotas.add(docec);
        docec.setText("12 Cuotas");
        jPanel2.add(docec);
        docec.setBounds(140, 30, 120, 23);

        grupocuotas.add(tresc);
        tresc.setText("3 Cuotas");
        jPanel2.add(tresc);
        tresc.setBounds(0, 0, 110, 23);

        grupocuotas.add(diezc);
        diezc.setText("10 Cuotas");
        jPanel2.add(diezc);
        diezc.setBounds(0, 30, 110, 23);

        grupocuotas.add(seisc);
        seisc.setText("6 Cuotas");
        jPanel2.add(seisc);
        seisc.setBounds(140, 0, 120, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 430, 250, 80);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inclienteActionPerformed

    }//GEN-LAST:event_inclienteActionPerformed

    private void inclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inclienteKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try
            {
                int id=Integer.parseInt(incliente.getText());
                String nombre = new String();
                String apellido = new String();
                String direccion = new String();
                String nit = new String();

                boolean r;
                r=MetodosCliente.ExisteCodigoCliente(id);
                if(r==true)
                {
                    Statement ps=null;
                    ResultSet rs;

                    ps = Conexiones.Conexion.getConexion().createStatement();
                    rs = ps.executeQuery("select ccliente,ncliente,acliente,dcliente,nitcliente from clientes");
                    while (rs.next())
                    {
                        String ccliente = rs.getString("CCLIENTE");
                        int auxcodigo=Integer.parseInt(ccliente);
                        String n = rs.getString("NCLIENTE");
                        String a = rs.getString("ACLIENTE");
                        String d = rs.getString("DCLIENTE");
                        String ni = rs.getString("NITCLIENTE");
                        if(id==auxcodigo)
                        {
                            nombre=n;
                            apellido=a;
                            direccion=d;
                            nit=ni;
                        }
                    }
                    mcliente.setText(nombre+" "+apellido);
                    idir.setText(direccion);
                    init.setText(nit);
                    inproducto.requestFocus();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO, VERIFIQUE");
                    incliente.requestFocus();
                    mcliente.setText("");
                    idir.setText("");
                    init.setText("");
                }
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, "La BD tiene problemas" + e.getMessage(),
                    "Error de Base de Datos",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_inclienteKeyPressed

    private void inproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inproductoActionPerformed

    private void inproductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inproductoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try
            {
                int id=Integer.parseInt(inproducto.getText());
                boolean r;
                r=MetodosProducto.ExisteCodigoStock(id);
                if(r==true)
                {
                    mproducto.setText(MetodosProducto.MostrarProducto(id));
                    mprecio.setText(MetodosProducto.MostrarPrecioProducto(id));
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO, VERIFIQUE");
                    mproducto.setText("");
                    mprecio.setText("");
                }
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");

            }
        }
    }//GEN-LAST:event_inproductoKeyPressed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

        incliente.setText("");
        inproducto.setText("");
        mcliente.setText("");
        idir.setText("");
        init.setText("");
        mprecio.setText("");
        mproducto.setText("");
        mcuota.setText("");
        proyectopagos.VPrincipal mostrar = new proyectopagos.VPrincipal();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        try{
            int ccliente=Integer.parseInt(incliente.getText());
            String nombre=mcliente.getText();
            String direccion=idir.getText();
            String nit=init.getText();
            int cproducto=Integer.parseInt(inproducto.getText());
            String nproducto=mproducto.getText();
            double pproducto=Double.parseDouble(mprecio.getText());
            int cuotas=ncuotas;
            double mcuotas=Double.parseDouble(mcuota.getText()); 
            
            ResultSet rs;
            Statement existetabla = Conexiones.Conexion.getConexion().createStatement();
            rs = existetabla.executeQuery("select cfactura from factura");
            rs = existetabla.executeQuery("select ccontrato from contrato");
            
            proyectopagos.MetodosDocumentos.GrabarNuevaFactura(ccliente, nombre, direccion, nit, cproducto,
            nproducto, pproducto, cuotas, mcuotas);
            cfactura=MetodosDocumentos.CodigoUltimaFactura();
            
            proyectopagos.MetodosDocumentos.GrabarContrato(ccliente,cfactura,cuotas,mcuotas,pproducto);
            ccontrato=MetodosDocumentos.CodigoUltimoContrato();
            
            proyectopagos.MetodosDocumentos.GrabarFechas(ccontrato,cuotas);
            ingreso();
        }
        catch(NumberFormatException ex)
        {
                JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "La BD tiene problemas" + e.getMessage(),
            "Error de Base de Datos",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void bclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclienteActionPerformed
        // TODO add your handling code here:
        try
        {
            int id=Integer.parseInt(incliente.getText());
            String nombre = new String();
            String apellido = new String();
            String direccion = new String();
            String nit = new String();

            boolean r;
            r=MetodosCliente.ExisteCodigoCliente(id);
            if(r==true)
            {
                Statement ps=null;
                ResultSet rs;

                ps = Conexiones.Conexion.getConexion().createStatement();
                rs = ps.executeQuery("select ccliente,ncliente,acliente,dcliente,nitcliente from clientes");
                while (rs.next())
                {
                    String ccliente = rs.getString("CCLIENTE");
                    int auxcodigo=Integer.parseInt(ccliente);
                    String n = rs.getString("NCLIENTE");
                    String a = rs.getString("ACLIENTE");
                    String d = rs.getString("DCLIENTE");
                    String ni = rs.getString("NITCLIENTE");
                    if(id==auxcodigo)
                    {
                        nombre=n;
                        apellido=a;
                        direccion=d;
                        nit=ni;
                    }
                }
                mcliente.setText(nombre+" "+apellido);
                idir.setText(direccion);
                init.setText(nit);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO, VERIFIQUE");
                mcliente.setText("");
                idir.setText("");
                init.setText("");
            }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "La BD tiene problemas" + e.getMessage(),
                "Error de Base de Datos",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bclienteActionPerformed

    private void bproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bproductoActionPerformed
        // TODO add your handling code here:
        try{
            int id=Integer.parseInt(inproducto.getText());
            boolean r;
            r=MetodosProducto.ExisteCodigoStock(id);
            if(r==true)
            {
                mproducto.setText(MetodosProducto.MostrarProducto(id));
                mprecio.setText(MetodosProducto.MostrarPrecioProducto(id));

            }
            else
            {
                JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO, VERIFIQUE");
                mproducto.setText("");
                mprecio.setText("");
            }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
        }
    }//GEN-LAST:event_bproductoActionPerformed

    private void cclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cclienteActionPerformed
        // TODO add your handling code here:
        proyectopagos.IngresoC obj = new proyectopagos.IngresoC();
        obj.setVisible(true);
            proyectopagos.Venta ocultar = new proyectopagos.Venta();
            ocultar.setVisible(false);

    }//GEN-LAST:event_cclienteActionPerformed

    private void idirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idirActionPerformed

    private void ccuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccuotasActionPerformed
        // TODO add your handling code here:
        double cuotas=0;
        double precio=Double.parseDouble(mprecio.getText());

        if(tresc.isSelected())
        {
            cuotas=precio/3;
            //REDONDEAR PRECIO
            DecimalFormat formato = new DecimalFormat("#.00");
            int r = (int) Math.round(cuotas*100);
            cuotas = r / 100.0;
            ncuotas=3;
            mcuota.setText(String.valueOf(cuotas));
        }
        if(seisc.isSelected())
        {
            cuotas=precio/6;
            //REDONDEAR PRECIO
            DecimalFormat formato = new DecimalFormat("#.00");
            int r = (int) Math.round(cuotas*100);
            cuotas = r / 100.0;
            ncuotas=6;
            mcuota.setText(String.valueOf(cuotas));
        }
        if(diezc.isSelected())
        {
            cuotas=precio/10;
            //REDONDEAR PRECIO
            DecimalFormat formato = new DecimalFormat("#.00");
            int r = (int) Math.round(cuotas*100);
            cuotas = r / 100.0;
            ncuotas=10;
            mcuota.setText(String.valueOf(cuotas));
        }
        if(docec.isSelected())
        {
            cuotas=precio/12;
            //REDONDEAR PRECIO
            DecimalFormat formato = new DecimalFormat("#.00");
            int r = (int) Math.round(cuotas*100);
            cuotas = r / 100.0;
            ncuotas=12;
            mcuota.setText(String.valueOf(cuotas));
        }
    }//GEN-LAST:event_ccuotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcliente;
    private javax.swing.JButton bproducto;
    private javax.swing.JButton ccliente;
    private javax.swing.JButton ccuotas;
    private javax.swing.JRadioButton diezc;
    private javax.swing.JRadioButton docec;
    private javax.swing.ButtonGroup grupocuotas;
    private javax.swing.JTextField idir;
    private javax.swing.JTextField incliente;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel init;
    private javax.swing.JTextField inproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mcliente;
    private javax.swing.JLabel mcuota;
    private javax.swing.JButton menu;
    private javax.swing.JLabel mprecio;
    private javax.swing.JLabel mproducto;
    private javax.swing.JLabel precio;
    private javax.swing.JRadioButton seisc;
    private javax.swing.JRadioButton tresc;
    // End of variables declaration//GEN-END:variables
}
