/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopagos;

import java.awt.Dimension;
import java.awt.Window;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.FocusManager;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author fernando
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
        this.setSize(new Dimension(650, 550));
        this.setMinimumSize(new Dimension(500, 400));
        saldos.setEnabled(false);
        deudores.setEnabled(false);
        mejorcliente.setEnabled(false);
        peorcliente.setEnabled(false);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bfactura = new javax.swing.JButton();
        cproducto = new javax.swing.JButton();
        ccliente = new javax.swing.JButton();
        cstock = new javax.swing.JButton();
        deudores = new javax.swing.JButton();
        saldos = new javax.swing.JButton();
        mejorcliente = new javax.swing.JButton();
        peorcliente = new javax.swing.JButton();
        vender1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bfactura.setText("Buscar Factura/Contrato");
        bfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfacturaActionPerformed(evt);
            }
        });
        getContentPane().add(bfactura);
        bfactura.setBounds(320, 150, 160, 47);

        cproducto.setText("Crear Producto");
        cproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cproductoActionPerformed(evt);
            }
        });
        getContentPane().add(cproducto);
        cproducto.setBounds(122, 29, 129, 47);

        ccliente.setText("Crear Cliente");
        ccliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cclienteActionPerformed(evt);
            }
        });
        getContentPane().add(ccliente);
        ccliente.setBounds(319, 29, 130, 47);

        cstock.setText("Crear Existencia de Producto");
        cstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstockActionPerformed(evt);
            }
        });
        getContentPane().add(cstock);
        cstock.setBounds(181, 87, 185, 50);

        deudores.setText("Deudores");
        deudores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deudoresActionPerformed(evt);
            }
        });
        getContentPane().add(deudores);
        deudores.setBounds(320, 220, 160, 44);

        saldos.setText("Saldos");
        saldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldosActionPerformed(evt);
            }
        });
        getContentPane().add(saldos);
        saldos.setBounds(130, 220, 120, 44);

        mejorcliente.setText("Mejor Cliente");
        mejorcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejorclienteActionPerformed(evt);
            }
        });
        getContentPane().add(mejorcliente);
        mejorcliente.setBounds(320, 280, 160, 44);

        peorcliente.setText("Peor Cliente");
        peorcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peorclienteActionPerformed(evt);
            }
        });
        getContentPane().add(peorcliente);
        peorcliente.setBounds(130, 280, 120, 48);

        vender1.setText("Vender");
        vender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vender1ActionPerformed(evt);
            }
        });
        getContentPane().add(vender1);
        vender1.setBounds(130, 150, 119, 47);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfacturaActionPerformed
        // TODO add your handling code here:
        Consultas.BuscarFactura obj = new Consultas.BuscarFactura();
        obj.setVisible(true);
            
            this.setVisible(false);
            
    }//GEN-LAST:event_bfacturaActionPerformed

    private void cproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cproductoActionPerformed
        // TODO add your handling code here:
        
        proyectopagos.IngresoP obj = new proyectopagos.IngresoP();
        obj.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_cproductoActionPerformed

    private void cclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cclienteActionPerformed
        // TODO add your handling code here:
        proyectopagos.IngresoC obj = new proyectopagos.IngresoC();
        obj.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_cclienteActionPerformed

    private void cstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstockActionPerformed
        // TODO add your handling code here:
        proyectopagos.Ingreso_Stock obj = new proyectopagos.Ingreso_Stock();
        obj.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_cstockActionPerformed

    private void deudoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deudoresActionPerformed
        // TODO add your handling code here:
        Consultas.Deudores obj = new Consultas.Deudores();
        obj.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_deudoresActionPerformed

    private void saldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldosActionPerformed
        // TODO add your handling code here:
        Consultas.Saldos obj = new Consultas.Saldos();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saldosActionPerformed

    private void mejorclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejorclienteActionPerformed
        // TODO add your handling code here:
        Consultas.MejorCliente obj = new Consultas.MejorCliente();
        obj.setVisible(true);
        this.setVisible(false);    
        
    }//GEN-LAST:event_mejorclienteActionPerformed

    private void peorclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peorclienteActionPerformed
        // TODO add your handling code here:
        Consultas.PeorCliente obj = new Consultas.PeorCliente();
        obj.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_peorclienteActionPerformed

    private void vender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vender1ActionPerformed
        proyectopagos.Venta obj = new proyectopagos.Venta();
        obj.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_vender1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bfactura;
    private javax.swing.JButton ccliente;
    private javax.swing.JButton cproducto;
    private javax.swing.JButton cstock;
    private javax.swing.JButton deudores;
    private javax.swing.JButton mejorcliente;
    private javax.swing.JButton peorcliente;
    private javax.swing.JButton saldos;
    private javax.swing.JButton vender1;
    // End of variables declaration//GEN-END:variables
}
