/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author ferajset
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        transparenciaButton();
        transparenciaTextField();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        ingreso_user = new javax.swing.JTextField();
        ingreso_pass = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        fb1 = new javax.swing.JLabel();
        fb2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 230));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setIcon(new javax.swing.ImageIcon("/home/ferajset/Programacion/1.UMG/Login/src/main/java/recursos/login.png")); // NOI18N
        login.setText("jLabel2");
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 152, 150));

        ingreso_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_userActionPerformed(evt);
            }
        });
        jPanel1.add(ingreso_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 210, 30));
        jPanel1.add(ingreso_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, 30));

        salir.setBackground(new java.awt.Color(0, 0, 153));
        salir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salirMouseReleased(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 30));

        ingresar.setBackground(new java.awt.Color(0, 0, 153));
        ingresar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("Ingresar");
        ingresar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ingresarMouseDragged(evt);
            }
        });
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ingresarMouseReleased(evt);
            }
        });
        jPanel1.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 30));

        fb1.setIcon(new javax.swing.ImageIcon("/home/ferajset/Programacion/1.UMG/Login/src/main/java/recursos/Botton.png")); // NOI18N
        fb1.setText("jLabel2");
        jPanel1.add(fb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 30));

        fb2.setIcon(new javax.swing.ImageIcon("/home/ferajset/Programacion/1.UMG/Login/src/main/java/recursos/Botton.png")); // NOI18N
        fb2.setText("jLabel2");
        jPanel1.add(fb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 30));

        user.setText("Usuario");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        pass.setText("Contraseña");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon("/home/ferajset/Programacion/1.UMG/Login/src/main/java/recursos/fondo2.png")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingreso_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_userActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ingreso_userActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseClicked
        ingresar.setContentAreaFilled(true);
        ingresar.setBorderPainted(false);

    }//GEN-LAST:event_ingresarMouseClicked

    private void ingresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMousePressed

    }//GEN-LAST:event_ingresarMousePressed

    private void ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseExited
        ingresar.setContentAreaFilled(false);
    }//GEN-LAST:event_ingresarMouseExited

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setContentAreaFilled(false);
    }//GEN-LAST:event_salirMouseExited

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        salir.setContentAreaFilled(true);
    }//GEN-LAST:event_salirMouseClicked

    private void ingresarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseDragged

    }//GEN-LAST:event_ingresarMouseDragged

    private void salirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseReleased
        salir.setContentAreaFilled(false);
    }//GEN-LAST:event_salirMouseReleased

    private void ingresarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseReleased
        ingresar.setContentAreaFilled(false);
    }//GEN-LAST:event_ingresarMouseReleased

    public void transparenciaButton() {
        ingresar.setOpaque(false);
        ingresar.setContentAreaFilled(false);
        ingresar.setBorderPainted(false);
        salir.setOpaque(false);
        salir.setContentAreaFilled(false);
        salir.setBorderPainted(false);
    }

    public void transparenciaTextField() {
        ingreso_user.setOpaque(false);
        // ingreso_user.setBorderPainted(false);
        ingreso_pass.setOpaque(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fb1;
    private javax.swing.JLabel fb2;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresar;
    private javax.swing.JTextField ingreso_pass;
    private javax.swing.JTextField ingreso_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel pass;
    private javax.swing.JButton salir;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
