/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import conexiones.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ferajset
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        this.icono = new ImageIcon(getClass().getResource("/imagenes/ok.png"));
        initComponents();
        transparenciaButton();
    }
    Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        ingreso_user = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        fb1 = new javax.swing.JLabel();
        fb2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        ingreso_pass = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 230));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        login.setText("jLabel2");
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 152, 150));

        ingreso_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_userActionPerformed(evt);
            }
        });
        jPanel1.add(ingreso_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 210, 30));
        ingreso_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_pass.requestFocus();
            }
        });

        salir.setBackground(new java.awt.Color(0, 0, 153));
        salir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 30));

        ingresar.setBackground(new java.awt.Color(0, 0, 153));
        ingresar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 30));

        fb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Botton.png"))); // NOI18N
        fb1.setText("jLabel2");
        jPanel1.add(fb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 30));

        fb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Botton.png"))); // NOI18N
        fb2.setText("jLabel2");
        jPanel1.add(fb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 30));

        user.setText("Usuario");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        pass.setText("Contraseña");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        ingreso_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_passActionPerformed(evt);
            }
        });
        jPanel1.add(ingreso_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, 30));
        ingreso_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_passActionPerformed(evt);
                if (ingreso_user.getText().equalsIgnoreCase("") || ingreso_pass.getText().equalsIgnoreCase("")) {
                    JOptionPane.showMessageDialog(null, "No se aceptan campos vacios",
                        "Error de datos", JOptionPane.ERROR_MESSAGE);
                    ingreso_user.setText("");
                    ingreso_pass.setText("");
                    ingreso_user.requestFocus();
                } else {
                    //   useMySql();     //llama a la conexión implementada para MySql
                    useOracleSql(); //llama a la conexión implementada para OracleSql
                }
            }
        });

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingreso_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_userActionPerformed

    }//GEN-LAST:event_ingreso_userActionPerformed
    
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    public void useMySql() {
        ConexionBD conn = new ConexionMySql_I();
        conn.getConnection(ingreso_user.getText(), ingreso_pass.getText());
        if (conn.status() != false) {
            JOptionPane.showConfirmDialog(null, "Bienvenido " + ingreso_user.getText(), "Acceso Correcto", JOptionPane.CLOSED_OPTION);
        } else {
            ingreso_user.setText("");
            ingreso_pass.setText("");
        }
    }

    public void useOracleSql() {
        ConexionBD conn = new ConexionOracleSql_I();
        conn.getConnection(ingreso_user.getText(), ingreso_pass.getText());
        if (conn.status() != false) {
            JOptionPane.showConfirmDialog(null, "Bienvenido " + ingreso_user.getText(), "Acceso Correcto", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE, icono);
        } else {
            ingreso_user.setText("");
            ingreso_pass.setText("");
            ingreso_user.requestFocus();
        }
    }


    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        if (ingreso_user.getText().equalsIgnoreCase("") || ingreso_pass.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "No se aceptan campos vacios",
                    "Error de datos", JOptionPane.ERROR_MESSAGE);
            ingreso_user.setText("");
            ingreso_pass.setText("");
            ingreso_user.requestFocus();
        } else {
            //   useMySql();     //llama a la conexión implementada para MySql
            useOracleSql(); //llama a la conexión implementada para OracleSql
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void ingreso_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreso_passActionPerformed

    public void transparenciaButton() {
        ingresar.setOpaque(false);
        ingresar.setContentAreaFilled(false);
        ingresar.setBorderPainted(false);
        salir.setOpaque(false);
        salir.setContentAreaFilled(false);
        salir.setBorderPainted(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fb1;
    private javax.swing.JLabel fb2;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresar;
    private javax.swing.JPasswordField ingreso_pass;
    private javax.swing.JTextField ingreso_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel pass;
    private javax.swing.JButton salir;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
