/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author balvarado
 */
public class Inicio extends javax.swing.JFrame {

    HashCerrada h1 = new HashCerrada(15);

    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nlibro = new javax.swing.JLabel();
        npclave = new javax.swing.JLabel();
        libroing = new javax.swing.JLabel();
        npclaveing = new javax.swing.JTextField();
        nlibroing = new javax.swing.JTextField();
        savenl = new javax.swing.JButton();
        separador1 = new javax.swing.JLabel();
        bxlibro = new javax.swing.JLabel();
        pclavecont = new javax.swing.JLabel();
        blibro = new javax.swing.JLabel();
        rblibro = new javax.swing.JTextField();
        respclave = new javax.swing.JTextField();
        blibroxtit = new javax.swing.JButton();
        separadorno2 = new javax.swing.JLabel();
        bxpclave = new javax.swing.JLabel();
        pclaveb = new javax.swing.JLabel();
        respclaveb = new javax.swing.JTextField();
        librosxpclave = new javax.swing.JLabel();
        reslibrosxpclave = new javax.swing.JTextField();
        bcoinc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(547, 577));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 510, 70, 0);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 20, 70, 0);

        nlibro.setText("INGRESO DE UN NUEVO LIBRO");
        getContentPane().add(nlibro);
        nlibro.setBounds(180, 10, 220, 30);

        npclave.setText("Palabras clave:");
        getContentPane().add(npclave);
        npclave.setBounds(30, 90, 170, 20);

        libroing.setText("Título a ingresar:");
        getContentPane().add(libroing);
        libroing.setBounds(30, 60, 170, 20);
        getContentPane().add(npclaveing);
        npclaveing.setBounds(140, 90, 350, 30);
        getContentPane().add(nlibroing);
        nlibroing.setBounds(140, 50, 350, 30);

        savenl.setText("Guardar Nuevo Libro");
        savenl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savenlActionPerformed(evt);
            }
        });
        getContentPane().add(savenl);
        savenl.setBounds(160, 130, 220, 23);

        separador1.setText("*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*");
        getContentPane().add(separador1);
        separador1.setBounds(0, 170, 550, 14);

        bxlibro.setText("BUSQUEDA DE LIBRO POR TÍTULO");
        getContentPane().add(bxlibro);
        bxlibro.setBounds(180, 190, 240, 30);

        pclavecont.setText("Palabras que contiene el libro buscado:");
        getContentPane().add(pclavecont);
        pclavecont.setBounds(30, 280, 230, 14);

        blibro.setText("Título del libro:");
        getContentPane().add(blibro);
        blibro.setBounds(30, 220, 110, 14);
        getContentPane().add(rblibro);
        rblibro.setBounds(140, 220, 360, 30);
        getContentPane().add(respclave);
        respclave.setBounds(260, 270, 240, 40);

        blibroxtit.setText("Buscar Libro");
        blibroxtit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blibroxtitActionPerformed(evt);
            }
        });
        getContentPane().add(blibroxtit);
        blibroxtit.setBounds(30, 250, 110, 20);

        separadorno2.setText("*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*");
        getContentPane().add(separadorno2);
        separadorno2.setBounds(0, 320, 550, 14);

        bxpclave.setText("BUSQUEDA DE LIBRO POR PALABRA CLAVE");
        getContentPane().add(bxpclave);
        bxpclave.setBounds(170, 340, 310, 20);

        pclaveb.setText("Palabras clave a buscar:");
        getContentPane().add(pclaveb);
        pclaveb.setBounds(30, 360, 180, 14);
        getContentPane().add(respclaveb);
        respclaveb.setBounds(170, 360, 320, 30);

        librosxpclave.setText("Los libros que contienen estas palabras son:");
        getContentPane().add(librosxpclave);
        librosxpclave.setBounds(30, 430, 290, 20);
        getContentPane().add(reslibrosxpclave);
        reslibrosxpclave.setBounds(30, 450, 470, 50);

        bcoinc.setText("Buscar Coincidencias");
        bcoinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcoincActionPerformed(evt);
            }
        });
        getContentPane().add(bcoinc);
        bcoinc.setBounds(30, 400, 170, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void buscarClave(String clave){
                String busqueda = clave;
        String respuesta = new String();
        String arregloPalabras[] = busqueda.split(",");
        for (int i = 0; i < arregloPalabras.length; i++) {
            //this.palabras.insertar(arregloPalabras[i]);
            if (h1.buscarClave(arregloPalabras[i]).isEmpty() == false) {
                // System.out.println("si hay");
                respuesta += arregloPalabras[i] + " esta en: " + h1.buscarClave(arregloPalabras[i]) + "\n";
            }

        }

        if (respuesta.isEmpty() == false) {
            //System.out.println(respuesta);
            reslibrosxpclave.setText(respuesta);
        } else {
            JOptionPane.showMessageDialog(null, "No Hay Coincidencias");
                reslibrosxpclave.setText(null);
          //  System.out.println("No hay");
        }
    }
    
    
    private void savenlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savenlActionPerformed
        String tLibro = nlibroing.getText();
        String palabras = npclaveing.getText();

        if (tLibro.isEmpty() == false) {
            if (palabras.isEmpty() == false) {
                h1.Ingresar(tLibro, palabras);
                JOptionPane.showMessageDialog(null, "GUARDADO CON EXITO");
                nlibroing.setText(null);
                npclaveing.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "No se ingresaron palabras");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ingresó Titulo");
        }
    }//GEN-LAST:event_savenlActionPerformed

    private void blibroxtitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blibroxtitActionPerformed
        String bLibro = rblibro.getText();
        String mPalabras = new String();
        NodoLista Respuesta;
        if (bLibro.isEmpty() == false) {
            Respuesta = h1.BuscarTitulo(bLibro);
            if (Respuesta != null) {
                mPalabras=Respuesta.palabras.Preorden();
                respclave.setText(mPalabras);
            } else {
                JOptionPane.showMessageDialog(null, "No Hay Coincidencias");
                rblibro.setText(null);
                respclave.setText(null);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha ingresado datos para buscar");
        }

    }//GEN-LAST:event_blibroxtitActionPerformed

    private void bcoincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcoincActionPerformed
        String bLibro=respclaveb.getText();
        
        if(bLibro.isEmpty()==false){
            buscarClave(bLibro);
        }
        else {
            JOptionPane.showMessageDialog(null, "No ha ingresado datos para buscar");
        }
        
    }//GEN-LAST:event_bcoincActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcoinc;
    private javax.swing.JLabel blibro;
    private javax.swing.JButton blibroxtit;
    private javax.swing.JLabel bxlibro;
    private javax.swing.JLabel bxpclave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel libroing;
    private javax.swing.JLabel librosxpclave;
    private javax.swing.JLabel nlibro;
    private javax.swing.JTextField nlibroing;
    private javax.swing.JLabel npclave;
    private javax.swing.JTextField npclaveing;
    private javax.swing.JLabel pclaveb;
    private javax.swing.JLabel pclavecont;
    private javax.swing.JTextField rblibro;
    private javax.swing.JTextField reslibrosxpclave;
    private javax.swing.JTextField respclave;
    private javax.swing.JTextField respclaveb;
    private javax.swing.JButton savenl;
    private javax.swing.JLabel separador1;
    private javax.swing.JLabel separadorno2;
    // End of variables declaration//GEN-END:variables
}
