#include<iostream>
#include<conio.h>

int main(){
   int entero=15;    		//variable numeros enteros
   float flotante=10.45;   //variable decimales   7 digitos contando el punto
   double mayor=16.3456;   //variable de muchos decimales
   char letra='B';  			//variable 1 caracter  letra, numero o símbolo

   //cout<<entero<< endl;

   //cout<<flotante;

   //cout<<mayor;

   cout<<letra;

getch();

return 0;
}
