# include<iostream>
# include<conio.h>
# include<math.h>

int main()
{
cout<<"Ingresa tu fecha de naciemiento\n";
 int dia;

int mes;

int anio;

cout<<"ingrese el numero de día: \n";
cin>>dia;
cout<<"ingrese el numero de mes: \n";
cin>>mes;
cout<<"ingrese el año: \n";
cin>>anio;

cout<<"Tu cumpleaños es el: \n";
cout<<dia;
cout<<"/";
cout<<mes;

cout<<"naciste en el año de: \n"
cout<<anio;
getch();
}