
SELECT DISTINCT nationality FROM authors;

#ACTUALIZANDO PAIS PARA QUE GBR Y ENG SEAN LO MISMO
UPDATE authors 
SET nationality='GBR'
WHERE nationality='ENG'
;

#CONTANDO CUANTOS LIBROS HAY
SELECT COUNT(book_id), SUM(1) FROM books
;

#SUMANDO TODOS LOS PRECIOS DE LIBROS VENDIDOS
SELECT SUM(price) FROM books
WHERE sellable=1
;

#ESTIMADO DEL MONTO EN INVENTARIO, HACIENDO SUMA DE PRECIOS DE LIBROS VENDIBLES POR CANTIDAD DE UNIDADES POR LIBROS
SELECT SUM(price*copies) FROM books
WHERE sellable=1
;

#AGRUPANDO MONTO DE INVENTARIO POR VENDIBLES Y NO VENDIBLES
SELECT sellable, sum(price*copies) 
FROM books
GROUP BY sellable
;

#CONTANDO CUANTOS LIBROS HAY, CUANTOS LIBROS SON MENOR A 1950 Y CUANTOS SON MAYOR A 1950
SELECT COUNT(book_id), 
SUM(if(YEAR<1950, 1, 0)) AS '<1950',
SUM(if(YEAR<1950, 0, 1)) AS '>1950'
FROM books
;

#CONTANDO LO MISMO DE LA ANTERIOR, PERO USANDO WHERE
SELECT count(book_id) 
FROM books
WHERE YEAR<1950
;

#HACER MATRIZ AGRUPANDO LIBROS POR RANGOS DE AÑOS
SELECT COUNT(book_id), 
SUM(IF(YEAR<1950, 1, 0)) AS '<1950',
SUM(IF(YEAR>=1950 AND YEAR<1990, 1, 0)) AS '<1990',
SUM(IF(YEAR>=1990 AND YEAR<2000, 1, 0)) AS '<2000',
SUM(IF(YEAR>=2000, 1,0)) AS '>2000'
FROM books
;

#MATRIZ QUE AGRUPA POR NACIONALIDAD, LA CANTIDAD DE LIBROS POR RANGOS DE AÑOS
SELECT a.nationality, COUNT(book_id) AS cantidad, 
SUM(IF(YEAR<1950, 1, 0)) AS '<1950',
SUM(IF(YEAR>=1950 AND YEAR<1990, 1, 0)) AS '<1990',
SUM(IF(YEAR>=1990 AND YEAR<2000, 1, 0)) AS '<2000',
SUM(IF(YEAR>=2000, 1,0)) AS '>2000'
FROM books AS b
JOIN authors AS a
    ON a.author_id=b.author_id
WHERE a.nationality IS NOT NULL
GROUP BY a.nationality
ORDER BY cantidad DESC
;   

