INSERT INTO REGIONS 
VALUES(5, 'NORTH POLE');

INSERT INTO REGIONS (REGION_ID, REGION_NAME)
VALUES(6, 'SOUTH POLE');

INSERT INTO REGIONS(REGION_ID, REGION_NAME)
SELECT 7,'Oceania' FROM DUAL;

UPDATE REGIONS SET REGION_NAME='Central America' WHERE REGION_ID=7;

ALTER TABLE REGIONS MODIFY REGION_NAME NOT NULL UNIQUE;

INSERT INTO REGIONS (REGION_ID, REGION_NAME)
VALUES(8, 'SOUTH POLE');

SELECT * FROM REGIONS;
DESCRIBE REGIONS;